-- 2026-09-10 길드원 라이프사이클/Discord 연결 이력
-- 적용 순서: 반드시 밍보드 코드 배포 전에 실행

begin;

create table if not exists public.guild_member_states (
  gid bigint primary key,
  status text not null default 'active'
    check (status in ('active', 'left', 'banned')),
  left_at timestamptz,
  updated_at timestamptz not null default now(),
  updated_by text,
  reason text
);

alter table public.guild_member_discord_links
  add column if not exists revoked_at timestamptz;

alter table public.guild_member_discord_links
  add column if not exists revoke_reason text;

create index if not exists idx_guild_member_discord_links_gid_active
  on public.guild_member_discord_links (gid)
  where revoked_at is null;

create index if not exists idx_guild_member_discord_links_discord_active
  on public.guild_member_discord_links (discord_id)
  where revoked_at is null;

create table if not exists public.member_access_history (
  id bigint generated by default as identity primary key,
  gid bigint,
  discord_id text,
  action text not null,
  detail text,
  created_at timestamptz not null default now()
);

create index if not exists idx_member_access_history_gid
  on public.member_access_history (gid, created_at desc);

create index if not exists idx_member_access_history_discord
  on public.member_access_history (discord_id, created_at desc);

update public.guild_member_discord_links
set
  revoked_at = null,
  revoke_reason = null
where revoked_at is null;

commit;
